name: Deploy to gelectric-main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: gelectric.co
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .
          target: /home/james/gelectric-website-main

      - name: SSH into gelectric.co and deploy gelectric-main
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: gelectric.co
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/james/gelectric-website-main
            docker-compose down
            docker-compose up -d
