name: Deploy to gelectric-staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: gelectric.co
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "resources/,src/python/,docker-compose.staging.yml,Dockerfile,requirements.txt"
          target: /home/james/gelectric-website-staging

      - name: SSH into gelectric.co and deploy gelectric-staging
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: gelectric.co
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/james/gelectric-website-staging
            docker-compose -f docker-compose.staging.yml down
            docker-compose -f docker-compose.staging.yml build
            docker-compose -f docker-compose.staging.yml up -d
